### ISSUE TITLE
Convert TypeScript experimental decorators to ES decorators

### ISSUE THREAD

**Issue by eamodio** [gitkraken/vscode-gitlens#2572]
Now that TypeScript 5 has proper ES decorator support we should rework our decorators into ES decorators.

```[tasklist]
### Tasks
- [ ] [@logName](https://github.com/gitkraken/vscode-gitlens/blob/3940ef7c20cb446cb1a6c9e490470e26c38b61d5/src/system/decorators/log.ts#L45)
- [ ] [@debug](https://github.com/gitkraken/vscode-gitlens/blob/3940ef7c20cb446cb1a6c9e490470e26c38b61d5/src/system/decorators/log.ts#L51)
- [ ] [@log](https://github.com/gitkraken/vscode-gitlens/blob/3940ef7c20cb446cb1a6c9e490470e26c38b61d5/src/system/decorators/log.ts#L57)
- [ ] [@command](https://github.com/gitkraken/vscode-gitlens/blob/be6ef592b007f7c4728ce481b8e32c7ad3d0588e/src/system/command.ts#L14)
- [ ] [@gate](https://github.com/gitkraken/vscode-gitlens/blob/f7ffae07a62d55fcb142a1aa6443563da59fde1f/src/system/decorators/gate.ts#L5)
- [ ] [@memoize](https://github.com/gitkraken/vscode-gitlens/blob/f7ffae07a62d55fcb142a1aa6443563da59fde1f/src/system/decorators/memoize.ts#L4)
- [ ] [@timeout](https://github.com/gitkraken/vscode-gitlens/blob/f7ffae07a62d55fcb142a1aa6443563da59fde1f/src/system/decorators/timeout.ts#L6)
- [ ] [@serialize](https://github.com/gitkraken/vscode-gitlens/blob/615b51a9b2c916bb37db7bd7cb7572d713298165/src/system/decorators/serialize.ts#L1)
```
