### ISSUE TITLE
ner

### ISSUE THREAD

**Issue by clutchfactorxxx** [gitkraken/vscode-gitlens#3604]
```[tasklist]
### Tasks
- [ ] https://github.com/gitkraken/vscode-gitlens/pull/3589
- [ ] https://github.com/gitkraken/vscode-gitlens/issues/3600
- [ ] https://github.com/gitkraken/vscode-gitlens/pull/3601
```
