### ISSUE TITLE
Walkthrough (onboarding checklist) revamp

### ISSUE THREAD

**Issue by d13** [gitkraken/vscode-gitlens#3656]
### Overview

This succeeds the home onboarding checklist in favor of updating our Walkthrough. We may still provide an progress indicator of the checked steps on the home view.

### References

[GitLens Onboarding Figma](https://www.figma.com/design/ZRm91LPm0zpyfLwM1wwMZZ/GitLens-Onboarding?node-id=780-3082&node-type=canvas&t=LLWYJyAqfFvO2ehD-0)

[Walkthrough Steps with Completion Triggers](https://docs.google.com/spreadsheets/d/1H0iqSkLAXSXeWfXyvGudwaemhLzfFb-5LQhS4xRQqU4/edit?gid=0#gid=0)

[Walkthrough Contributions Guide](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs)

### High-level TODOs

- 1st priority changes
  - [x] In the `package.json`, under `contributes > walkthroughs > welcome`, setup new walkthrough steps with actions and states
  - [x] Implement `completionEvents` based on spreadsheet's triggers + account state (this will probably be the most work)
- 2nd priority changes
  - [ ] Review step verbiage with product
  - [x] Add `media` for each step
